// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SetLiszt.Web.Data;

#nullable disable

namespace SetLiszt.Web.Migrations
{
    [DbContext(typeof(SetLisztDbContext))]
    [Migration("20250914033653_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GigProject", b =>
                {
                    b.Property<int>("GigsId")
                        .HasColumnType("integer")
                        .HasColumnName("gigs_id");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer")
                        .HasColumnName("projects_id");

                    b.HasKey("GigsId", "ProjectsId")
                        .HasName("pk_gig_project");

                    b.HasIndex("ProjectsId")
                        .HasDatabaseName("ix_gig_project_projects_id");

                    b.ToTable("gig_project");
                });

            modelBuilder.Entity("GigSet", b =>
                {
                    b.Property<int>("GigsId")
                        .HasColumnType("integer")
                        .HasColumnName("gigs_id");

                    b.Property<int>("SetsId")
                        .HasColumnType("integer")
                        .HasColumnName("sets_id");

                    b.HasKey("GigsId", "SetsId")
                        .HasName("pk_gig_set");

                    b.HasIndex("SetsId")
                        .HasDatabaseName("ix_gig_set_sets_id");

                    b.ToTable("gig_set");
                });

            modelBuilder.Entity("ProjectSet", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer")
                        .HasColumnName("projects_id");

                    b.Property<int>("SetsId")
                        .HasColumnType("integer")
                        .HasColumnName("sets_id");

                    b.HasKey("ProjectsId", "SetsId")
                        .HasName("pk_project_set");

                    b.HasIndex("SetsId")
                        .HasDatabaseName("ix_project_set_sets_id");

                    b.ToTable("project_set");
                });

            modelBuilder.Entity("ProjectSong", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer")
                        .HasColumnName("projects_id");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer")
                        .HasColumnName("songs_id");

                    b.HasKey("ProjectsId", "SongsId")
                        .HasName("pk_project_song");

                    b.HasIndex("SongsId")
                        .HasDatabaseName("ix_project_song_songs_id");

                    b.ToTable("project_song");
                });

            modelBuilder.Entity("SetLiszt.Web.Models.Gig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("HitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hit_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_gig");

                    b.ToTable("gig", (string)null);
                });

            modelBuilder.Entity("SetLiszt.Web.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("SetLiszt.Web.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_set");

                    b.ToTable("set", (string)null);
                });

            modelBuilder.Entity("SetLiszt.Web.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_song");

                    b.ToTable("song", (string)null);
                });

            modelBuilder.Entity("SetLiszt.Web.Models.SongFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filepath");

                    b.Property<int>("InstrumentTransposition")
                        .HasColumnType("integer")
                        .HasColumnName("instrument_transposition");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<int>("SongId")
                        .HasColumnType("integer")
                        .HasColumnName("song_id");

                    b.HasKey("Id")
                        .HasName("pk_song_file");

                    b.HasIndex("SongId")
                        .HasDatabaseName("ix_song_file_song_id");

                    b.ToTable("song_file", (string)null);
                });

            modelBuilder.Entity("SetSong", b =>
                {
                    b.Property<int>("SetsId")
                        .HasColumnType("integer")
                        .HasColumnName("sets_id");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer")
                        .HasColumnName("songs_id");

                    b.HasKey("SetsId", "SongsId")
                        .HasName("pk_set_song");

                    b.HasIndex("SongsId")
                        .HasDatabaseName("ix_set_song_songs_id");

                    b.ToTable("set_song");
                });

            modelBuilder.Entity("GigProject", b =>
                {
                    b.HasOne("SetLiszt.Web.Models.Gig", null)
                        .WithMany()
                        .HasForeignKey("GigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gig_project_gig_gigs_id");

                    b.HasOne("SetLiszt.Web.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gig_project_project_projects_id");
                });

            modelBuilder.Entity("GigSet", b =>
                {
                    b.HasOne("SetLiszt.Web.Models.Gig", null)
                        .WithMany()
                        .HasForeignKey("GigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gig_set_gig_gigs_id");

                    b.HasOne("SetLiszt.Web.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gig_set_set_sets_id");
                });

            modelBuilder.Entity("ProjectSet", b =>
                {
                    b.HasOne("SetLiszt.Web.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_set_project_projects_id");

                    b.HasOne("SetLiszt.Web.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_set_set_sets_id");
                });

            modelBuilder.Entity("ProjectSong", b =>
                {
                    b.HasOne("SetLiszt.Web.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_song_project_projects_id");

                    b.HasOne("SetLiszt.Web.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_song_song_songs_id");
                });

            modelBuilder.Entity("SetLiszt.Web.Models.SongFile", b =>
                {
                    b.HasOne("SetLiszt.Web.Models.Song", null)
                        .WithMany("SongFiles")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_song_file_song_song_id");
                });

            modelBuilder.Entity("SetSong", b =>
                {
                    b.HasOne("SetLiszt.Web.Models.Set", null)
                        .WithMany()
                        .HasForeignKey("SetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_set_song_set_sets_id");

                    b.HasOne("SetLiszt.Web.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_set_song_song_songs_id");
                });

            modelBuilder.Entity("SetLiszt.Web.Models.Song", b =>
                {
                    b.Navigation("SongFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
